### PR TITLE
Better Navbar with more consistency fonts and color

### PR DESCRIPTION
**Pull request by cxde-Sujal**
Issue - #8 

I have created a better Navbar you can check the current one and the updated one :
**Old Navbar**
Screenshot (233)
**Updated Navbar**
Screenshot (235)
@anjalit03 merge it for Hacktober ma'am.

### CODE REVIEW

**Comment by anjalit03** [comment]
yes it is good. but please fix this the home is highlighted on every page but the page that is open should be highlighted only please correct this

**Comment by anjalit03** [comment]
also the navbar is not aligned on the login page
Screenshot 2024-10-28 215129

**Comment by cxde-Sujal** [comment]
@anjalit03 can you merge it now i have made it across all pages 


Screenshot (235)
Screenshot (238)
Screenshot (240)
Screenshot (241)
Screenshot (242)

**Comment by anjalit03** [comment]
no no I told you to highlight the pages name like on home home should be highlighted on new event "new event" should be highlighted and so on....

**Comment by cxde-Sujal** [comment]
@anjalit03 the  navbar across pages is perfect but na?

**Comment by cxde-Sujal** [comment]
@anjalit03 it was not looking good so i decided to remove from home too ? Because too much hover is making it look bad to keep it plain and simple i have removed it is it fine?

**Pull request merged**
