### PR TITLE
displaying a thankyou message

### PR DESCRIPTION
**Pull request by Shreyhac**
i have fixed the error that displays a thank you message after a correct email has been entered 

Screenshot 2024-10-30 at 16 48 31

### CODE REVIEW

**Comment by anjalit03** [comment]
can you change the color of the message or maybe highlight it as it kind of mixes with the background.....

**Comment by Shreyhac** [comment]
Yes yes I can

**Comment by Shreyhac** [comment]
please check and merge if possible

**Comment by Shreyhac** [comment]
hey please merge the changes if possible before 12 am today

**Pull request merged**
